import { FARMER_SEASON, ORCHARD_SEASON, STUDY_UNLOCK_WORKERS, TREE_UNLOCK_FRUIT } from '../balance';
import type { BuildingDef, CraftDef, JobDef } from '../defs';

// 页面里的顺序按出现先后，这里的顺序不影响显示。

export const BUILDINGS: BuildingDef[] = [
  // ---- 农场 ----
  { id: 'tree', name: '果树', tab: 'farm', desc: '每棵每秒 +1 果子，冬天不结果',
    cost: { fruit: 10 }, ratio: 1.15, prod: { fruit: 1 }, group: 'orchard', season: ORCHARD_SEASON, weather: true,
    show: g => g.s.res.fruit >= TREE_UNLOCK_FRUIT || g.count('tree') > 0,
    intro: '地上落了不少果核。也许可以种。', first: '种下了第一棵树。它自己会结果。' },
  { id: 'timber', name: '林木', tab: 'farm', desc: '每棵每秒 +0.5 木头',
    cost: { fruit: 50 }, ratio: 1.15, prod: { wood: 0.5 }, group: 'forest',
    show: g => g.s.level >= 1, first: '坡上种了第一棵林木。木头不用自己砍了。' },
  { id: 'peach', name: '桃树', tab: 'farm', desc: '每棵每秒 +4 果子，夏天最多',
    cost: { fruit: 1500, wood: 150 }, ratio: 1.18, prod: { fruit: 4 }, group: 'orchard', season: [0.5, 2, 1, 0], weather: true,
    show: g => g.has('grafting'), first: '种下了第一棵桃树。' },
  { id: 'citrus', name: '柑橘树', tab: 'farm', desc: '每棵每秒 +6 果子，冬天最多',
    cost: { fruit: 20000, wood: 2000 }, ratio: 1.18, prod: { fruit: 6 }, group: 'orchard', season: [0.75, 0.5, 1, 1.75], weather: true,
    show: g => g.has('citrus'), first: '种下了第一棵柑橘树。冬天也有果子收了。' },
  { id: 'clayPit', name: '土坑', tab: 'farm', desc: '每个每秒 +0.3 黏土',
    cost: { wood: 150 }, ratio: 1.2, prod: { clay: 0.3 }, group: 'clay',
    show: g => g.has('brickmaking'), first: '在后坡挖了个土坑，黏土慢慢渗出来。' },
  { id: 'forestFarm', name: '林场', tab: 'farm', desc: '每座每秒 +8 木头',
    cost: { plank: 300, money: 300000 }, ratio: 1.3, prod: { wood: 8 }, group: 'forest',
    show: g => g.has('plantation'), first: '承包了后山的荒坡，种上了速生林。' },
  { id: 'elite', name: '良种果树', tab: 'farm', desc: '每棵每秒 +30 果子，冬天也结一点',
    cost: { seedling: 1, fruit: 2000000 }, ratio: 1.15, prod: { fruit: 30 }, group: 'orchard', season: [1, 1.25, 1.5, 0.25], weather: true,
    show: g => g.s.made.includes('seedling'), first: '良种苗木种下去了，农科院的人说三年就能挂果。' },
  { id: 'nursery', name: '苗圃', tab: 'farm', desc: '每秒用 500 果子、2 化肥育 0.02 株良种苗木',
    cost: { plank: 3000, money: 50000000 }, ratio: 1.4, use: { fruit: 500, fertilizer: 2 }, prod: { seedling: 0.02 },
    show: g => g.has('nursery'), first: '自己的苗圃育出了第一批苗木。' },
  { id: 'lease', name: '承包地', tab: 'farm', desc: '每块每秒交 100 钱租金，产 200 果子',
    cost: { money: 200000000 }, ratio: 1.3, upkeep: { money: 100 }, prod: { fruit: 200 }, group: 'orchard',
    season: ORCHARD_SEASON, weather: true,
    show: g => g.has('cooperative'), first: '和邻村签了承包合同，坡那边的地也归你管了。' },
  // ---- 年代五：现代农业 ----
  { id: 'sensor', name: '物联网传感器', tab: 'farm', desc: '每套每秒 +0.5 数据',
    cost: { plank: 5000, money: 100000000 }, ratio: 1.25, prod: { data: 0.5 }, group: 'data',
    show: g => g.has('smartFarming'), first: '果园里插满了传感器，土壤湿度、光照、虫情都传到了手机上。' },
  { id: 'excavator', name: '挖掘机', tab: 'farm', desc: '每台每秒 +20 黏土',
    cost: { money: 50000000 }, ratio: 1.3, prod: { clay: 20 }, group: 'clay',
    show: g => g.has('precast'), first: '挖掘机开上了后坡，一铲子顶十个人。' },
  { id: 'spaceOrchard', name: '太空果树', tab: 'farm', desc: '每棵每秒 +300 果子，冬天也结一半',
    cost: { spaceSeed: 1, fruit: 10000000 }, ratio: 1.2, prod: { fruit: 300 }, group: 'orchard',
    season: [1, 1.25, 1.5, 0.5], weather: true,
    show: g => g.s.f.space, first: '太空种子种下去了，长出来的苗比普通的壮一圈。' },
  { id: 'greenhouse', name: '温室', tab: 'farm', desc: '每间每秒 +15 果子，四季一样',
    cost: { plank: 300, brick: 300, money: 50000 }, ratio: 1.3, prod: { fruit: 15 }, group: 'orchard',
    show: g => g.has('greenhouse'), first: '第一间温室搭好了。外面下雪，里面开花。' },

  // ---- 帮工 ----
  { id: 'hut', name: '工棚', tab: 'crew', desc: '每间住 2 个帮工，每人每秒吃 0.5 个果子',
    cost: { wood: 50, money: 30 }, ratio: 1.6, housing: 2,
    show: g => g.owns('saw'),
    intro: '村里的年轻人听说你这儿缺人手，问有没有地方住。', first: '在果园边上搭了间工棚。' },
  { id: 'canteen', name: '食堂', tab: 'crew', desc: '每间心情 +3%',
    cost: { brick: 100, plank: 100, money: 20000 }, ratio: 1.6, mood: 0.03,
    show: g => g.s.f.mood, first: '食堂开张了，大锅饭比各自开伙香多了。' },
  { id: 'apartment', name: '员工公寓', tab: 'crew', desc: '每栋住 20 个帮工',
    cost: { brick: 5000, money: 50000000 }, ratio: 1.3, housing: 20,
    show: g => g.has('apartment'), first: '员工公寓封顶了，六层楼，带电梯。' },
  { id: 'clinic', name: '卫生所', tab: 'crew', desc: '每间心情 +5%',
    cost: { brick: 3000, money: 20000000 }, ratio: 1.6, mood: 0.05,
    show: g => g.s.f.family, first: '村里有了卫生所，头疼脑热不用跑县城了。' },
  { id: 'school', name: '小学', tab: 'crew', desc: '每所心情 +5%，每秒 +5 农技',
    cost: { brick: 5000, plank: 3000, money: 40000000 }, ratio: 1.6, mood: 0.05, prod: { science: 5 }, group: 'study',
    show: g => g.s.f.family, first: '小学开学了，帮工的孩子们背着书包从果园边走过。' },
  { id: 'house', name: '砖房', tab: 'crew', desc: '每间住 5 个帮工',
    cost: { brick: 60, plank: 40 }, ratio: 1.45, housing: 5,
    show: g => g.has('brickHouse'), first: '盖起了第一间砖房，帮工们住得舒服多了。' },

  // ---- 农技 ----
  { id: 'library', name: '书屋', tab: 'study', desc: '农技上限 +100，农技员 +5%',
    cost: { wood: 150, money: 150 }, ratio: 1.3, caps: { science: 100 }, boost: { study: 0.05 },
    show: g => g.s.workers >= STUDY_UNLOCK_WORKERS || g.count('library') > 0,
    intro: '帮工小张是农大毕业的，说仓库边上可以搭个书屋。', first: '书屋搭好了，小张把他的书都搬了过来。' },
  { id: 'station', name: '农技站', tab: 'study', desc: '农技上限 +1,000，农技员 +10%',
    cost: { brick: 200, plank: 150, money: 30000 }, ratio: 1.3, caps: { science: 1000 }, boost: { study: 0.1 },
    show: g => g.has('station'), first: '农技站挂牌了，县里的专家说有空会来看看。' },
  { id: 'lab', name: '实验田', tab: 'study', desc: '农技上限 +5,000，每块每秒 +1 农技',
    cost: { plank: 500, brick: 500, money: 500000 }, ratio: 1.3, caps: { science: 5000 }, prod: { science: 1 }, group: 'study',
    show: g => g.has('labField'), first: '划出一块实验田，专门试新品种、新种法。' },
  { id: 'dataCenter', name: '数据中心', tab: 'study', desc: '数据上限 +10,000',
    cost: { brick: 20000, money: 1000000000 }, ratio: 1.35, caps: { data: 10000 },
    show: g => g.has('bigData'), first: '数据中心的机柜嗡嗡地转起来了。' },
  { id: 'spaceBase', name: '航天育种基地', tab: 'study', desc: '每座每小时自己育出约 2 颗太空种子',
    cost: { data: 5000, money: 1000000000 }, ratio: 1.5, prod: { spaceSeed: 0.0005 },
    show: g => g.has('spaceBase'), first: '和航天研究院合办的育种基地挂牌了。' },

  // ---- 工坊 ----
  { id: 'sawmill', name: '锯木坊', tab: 'craft', desc: '每秒用 25 木头做 0.5 块木板',
    cost: { plank: 50, brick: 50, money: 5000 }, ratio: 1.3, use: { wood: 25 }, prod: { plank: 0.5 }, group: 'mill',
    show: g => g.has('sawmill'), first: '锯木坊转起来了。' },
  { id: 'kiln', name: '砖窑', tab: 'craft', desc: '每秒用 10 黏土、5 木头烧 0.5 块砖',
    cost: { brick: 80, money: 5000 }, ratio: 1.3, use: { clay: 10, wood: 5 }, prod: { brick: 0.5 }, group: 'mill',
    show: g => g.has('kiln'), first: '砖窑点上了火。' },
  { id: 'jamShop', name: '果酱作坊', tab: 'craft', desc: '每秒用 100 果子、10 木头熬 1 罐果酱',
    cost: { money: 100000 }, ratio: 1.6, use: { fruit: 100, wood: 10 }, prod: { jam: 1 }, group: 'mill',
    show: g => g.s.f.cooked, first: '在坡下盖了间果酱作坊。仓库里的果子和柴火，作坊自己会拿去熬。' },
  { id: 'coldStore', name: '冷库', tab: 'craft', desc: '果酱、果汁上限各 +1,000',
    cost: { brick: 500, plank: 300, money: 1000000 }, ratio: 1.4, caps: { jam: 1000, juice: 1000 },
    show: g => g.has('coldChain'), first: '冷库建好了，果酱能多放不少。' },
  { id: 'eshop', name: '网店', tab: 'market', desc: '网购顾客每秒多收 600 个果子的量',
    cost: { plank: 2000, money: 50000000 }, ratio: 1.35,
    show: g => g.has('ecommerce'), first: '网店开张了，第一单是从新疆下的。' },
  { id: 'fertFactory', name: '化肥厂', tab: 'craft', desc: '每秒用 20 黏土、2 包果干做 1 袋化肥',
    cost: { brick: 5000, money: 100000000 }, ratio: 1.4, use: { clay: 20, dried: 2 }, prod: { fertilizer: 1 }, group: 'mill',
    show: g => g.has('compoundFert'), first: '化肥厂投产了，不用再找商人换了。' },
  // ---- 农家乐 ----
  { id: 'homestay', name: '民宿', tab: 'resort', desc: '每间住 20 个游客',
    cost: { brick: 3000, plank: 2000, money: 30000000 }, ratio: 1.3, caps: { guest: 20 },
    show: g => g.s.f.tourism, first: '把老屋收拾成了民宿，第一批客人是从省城来的一家三口。' },
  { id: 'upick', name: '采摘园', tab: 'resort', desc: '每个吸引 15 个游客，秋天最多，冬天冷清',
    cost: { fruit: 5000000, money: 20000000 }, ratio: 1.3, appeal: 15, season: [1.2, 1, 1.5, 0.3],
    show: g => g.s.f.tourism, first: '划出一片果园做采摘园，门口立了块牌子：自己摘，按斤称。' },
  { id: 'restaurant', name: '农家饭庄', tab: 'resort', desc: '每间吸引 25 个游客，四季一样',
    cost: { brick: 5000, money: 80000000 }, ratio: 1.35, appeal: 25,
    show: g => g.has('ruralTourism'), first: '农家饭庄开张了，招牌菜是果酱烧排骨。' },
  { id: 'train', name: '观光小火车', tab: 'resort', desc: '每列吸引 60 个游客，冬天少',
    cost: { plank: 20000, money: 300000000 }, ratio: 1.4, appeal: 60, season: [1.3, 1.2, 1.3, 0.5],
    show: g => g.has('ruralTourism'), first: '小火车绕着果园跑一圈，孩子们坐了一趟又一趟。' },
  { id: 'resortHotel', name: '度假酒店', tab: 'resort', desc: '每栋住 150 个游客',
    cost: { brick: 20000, plank: 10000, money: 500000000 }, ratio: 1.35, caps: { guest: 150 },
    show: g => g.has('resortHotel'), first: '度假酒店开业了，房间的窗户正对着果园。' },
  { id: 'hotSpring', name: '温泉', tab: 'resort', desc: '每处吸引 80 个游客，冬天最旺',
    cost: { brick: 30000, money: 1000000000 }, ratio: 1.4, appeal: 80, season: [0.8, 0.3, 0.8, 2],
    show: g => g.has('hotSpring'), first: '后山打出了温泉，冬天泡着温泉看雪。' },

  { id: 'brickFactory', name: '砖厂', tab: 'craft', desc: '每秒用 50 黏土、5 木头烧 5 块砖',
    cost: { plank: 10000, money: 200000000 }, ratio: 1.35, use: { clay: 50, wood: 5 }, prod: { brick: 5 }, group: 'mill',
    show: g => g.has('precast'), first: '砖厂的隧道窑点火了，一天能出几十万块砖。' },
  { id: 'overseas', name: '海外仓', tab: 'market', desc: '海外市场每秒多收 1,000 个果子的量',
    cost: { brick: 20000, money: 1000000000 }, ratio: 1.35,
    show: g => g.has('crossBorder'), first: '第一个海外仓在新加坡开张了。' },
  { id: 'rack', name: '晒架', tab: 'craft', desc: '每秒用 50 果子晒 1 包果干，夏秋晒得快',
    cost: { plank: 200, money: 200000 }, ratio: 1.3, use: { fruit: 50 }, prod: { dried: 1 }, group: 'dry',
    season: [1, 1.5, 1.5, 0.25], weather: true,
    show: g => g.s.made.includes('dried'), first: '院子里搭起一排晒架。' },
  { id: 'juicer', name: '榨汁坊', tab: 'craft', desc: '每秒用 100 果子榨 1 瓶果汁',
    cost: { brick: 500, plank: 300, money: 2000000 }, ratio: 1.4, use: { fruit: 100 }, prod: { juice: 1 }, group: 'juice',
    show: g => g.s.made.includes('juice'), first: '榨汁坊开工了，满屋子果香。' },
  { id: 'cellar', name: '酒窖', tab: 'craft', desc: '果酒上限 +200',
    cost: { brick: 800, money: 5000000 }, ratio: 1.35, caps: { wine: 200 },
    show: g => g.has('brewing'), first: '在后山挖了个酒窖，冬暖夏凉。' },
  { id: 'winery', name: '酒坊', tab: 'craft', desc: '每秒用 200 果子、20 木头酿 0.2 瓶果酒',
    cost: { brick: 1000, plank: 800, money: 10000000 }, ratio: 1.45, use: { fruit: 200, wood: 20 }, prod: { wine: 0.2 }, group: 'winery',
    show: g => g.s.made.includes('wine'), first: '酒坊的发酵罐一排排立起来了。' }
];

export const JOBS: JobDef[] = [
  { id: 'farmer', name: '果农', desc: '每人每秒 +3 果子，冬天减半', prod: { fruit: 3 }, group: 'farmer',
    season: FARMER_SEASON, weather: true, show: g => g.s.workers > 0 },
  { id: 'woodcutter', name: '伐木工', desc: '每人每秒 +1 木头', prod: { wood: 1 }, group: 'forest',
    show: g => g.s.workers > 0 },
  { id: 'scholar', name: '农技员', desc: '每人每秒 +0.25 农技', prod: { science: 0.25 }, group: 'study',
    show: g => g.count('library') > 0 },
  { id: 'digger', name: '挖土工', desc: '每人每秒 +0.5 黏土', prod: { clay: 0.5 }, group: 'clay',
    show: g => g.has('brickmaking') },
  { id: 'seller', name: '推销员', desc: '每人每秒按最好的价卖掉 20 个果子', prod: {}, sells: 20,
    show: g => g.has('sales') }
];

export const CRAFTS: CraftDef[] = [
  { id: 'plank', name: '木板', cost: { wood: 50 }, out: 'plank', show: g => g.has('carpentry') },
  { id: 'brick', name: '砖', cost: { clay: 20, wood: 10 }, out: 'brick', show: g => g.has('brickmaking') },
  { id: 'jam', name: '果酱', cost: { fruit: 100, wood: 10 }, out: 'jam', show: g => g.has('jam') },
  { id: 'dried', name: '果干', cost: { fruit: 50 }, out: 'dried', show: g => g.has('drying'),
    first: '第一批果干晒好了，嚼起来甜甜的，帮工们抢着吃。' },
  { id: 'juice', name: '果汁', cost: { fruit: 100 }, out: 'juice', show: g => g.has('juicing'),
    first: '榨出了第一瓶果汁，装在玻璃瓶里，挺像样。' },
  { id: 'wine', name: '果酒', cost: { fruit: 200, wood: 20 }, out: 'wine', show: g => g.has('brewing') && g.count('cellar') > 0,
    first: '酿出第一瓶果酒，封进了酒窖。' },
  // 年代三：集市商人，销路饱和的时候出现。先跟商人换（手动），后面有化肥厂、苗圃（自动）
  { id: 'fertilizer', name: '农资商人', tab: 'market', cost: { money: 1000, dried: 10 }, out: 'fertilizer', amount: 20,
    remark: '果干换化肥，我们那边的人爱吃这个。', show: g => g.s.f.market,
    first: '从农资商人手里换来第一批化肥，撒在果树底下。仓库里有化肥，果园就一直施着肥。' },
  { id: 'seedling', name: '苗木商', tab: 'market', cost: { jam: 50, money: 20000 }, out: 'seedling',
    remark: '五十罐果酱换一株良种苗，省农科院的新品种。', show: g => g.s.f.market,
    first: '苗木商送来一株良种苗木，叮嘱要种在向阳的坡上。' }
];
