import type { TechDef } from '../defs';

/** 熬制：买了镇上的房、木头攒到这么多才会想到 */
export const JAM_UNLOCK_WOOD = 20000;

// 页面里的顺序按出现先后，这里的顺序不影响显示。
export const TECHS: TechDef[] = [
  { id: 'farming', name: '农时', desc: '果农 +25%', cost: { science: 30 }, deps: [],
    line: '记下了每样果子什么时候开花、什么时候该摘。', effects: { mult: { farmer: 0.25 } } },
  { id: 'grafting', name: '嫁接', desc: '果树 +20%，可以种桃树', cost: { science: 60 }, deps: [],
    line: '嫁接成活了。桃树也能种了，桃子夏天熟。', effects: { mult: { orchard: 0.2 } } },
  { id: 'carpentry', name: '木工', desc: '木头可以做成木板', cost: { science: 80 }, deps: [],
    line: '跟村里的木匠学会了刨木板。' },
  { id: 'brickmaking', name: '制砖', desc: '后坡的黏土可以烧砖', cost: { science: 100 }, deps: [],
    line: '后坡的土黏性好，能烧砖。' },
  { id: 'forestry', name: '育林', desc: '木头产量 +50%', cost: { science: 400 }, deps: ['carpentry'],
    line: '林木间伐，留大去小，木头长得更快。', effects: { mult: { forest: 0.5 } } },
  { id: 'bookkeeping', name: '记账', desc: '卖东西的价钱 +10%', cost: { science: 600 }, deps: ['farming'],
    line: '开始记账，才知道以前被压了多少价。', effects: { mult: { price: 0.1 } } },
  { id: 'brickHouse', name: '砖瓦房', desc: '可以盖砖房，每间住 5 人', cost: { science: 500 }, deps: ['carpentry', 'brickmaking'],
    line: '学会了砌墙上梁，能给帮工盖砖房了。' },
  { id: 'station', name: '农技站', desc: '可以建农技站', cost: { science: 800 }, deps: ['carpentry', 'brickmaking'],
    line: '县农业局同意在村里设个农技站。' },
  { id: 'citrus', name: '柑橘', desc: '可以种柑橘树，冬天产得最多', cost: { science: 1200 }, deps: ['grafting'],
    line: '从南边引来了柑橘苗，冬天也能有收成。' },
  { id: 'irrigation', name: '灌溉', desc: '果树 +15%，不怕旱', cost: { science: 1500, money: 20000 }, deps: ['grafting'],
    line: '挖了水渠，旱年也不怕了。', effects: { mult: { orchard: 0.15 }, flags: ['noDrought'] } },
  { id: 'pruning', name: '整形修剪', desc: '果树 +20%', cost: { science: 3000 }, deps: ['grafting'],
    line: '树冠修成开心形，通风透光，果子又大又甜。', effects: { mult: { orchard: 0.2 } } },
  { id: 'sawmill', name: '锯木坊', desc: '可以建锯木坊，自动做木板', cost: { science: 2000 }, deps: ['carpentry'],
    line: '画好了锯木坊的图纸。' },
  { id: 'kiln', name: '砖窑', desc: '可以建砖窑，自动烧砖', cost: { science: 2000 }, deps: ['brickmaking'],
    line: '学会了砌窑。' },
  { id: 'compost', name: '堆肥', desc: '果农 +25%，果树 +10%', cost: { science: 4000 }, deps: ['farming', 'brickmaking'],
    line: '落叶和果皮沤成肥，地越种越肥。', effects: { mult: { farmer: 0.25, orchard: 0.1 } } },
  { id: 'greenhouse', name: '温室', desc: '可以建温室，四季都结果', cost: { science: 6000 }, deps: ['citrus', 'brickHouse'],
    line: '温室的图纸画好了，木架子砖墙，顶上蒙塑料布。' },
  { id: 'meteorology', name: '气象', desc: '坏天气的影响减半', cost: { science: 8000 }, deps: ['farming', 'irrigation'],
    line: '装了个小气象站，看天吃饭心里有数了。', effects: { flags: ['halfBadWeather'] } },
  { id: 'sales', name: '推销', desc: '可以派帮工当推销员，自动卖果子', cost: { science: 5000 }, deps: ['farming'],
    show: g => g.owns('santana'),
    line: '派人去县里跑销路，买家不用等你上门了。' },
  { id: 'jam', name: '熬制', desc: '果子加木头熬成果酱，价钱是果子的 3 倍', cost: { science: 3000 }, deps: [],
    show: g => g.owns('townHouse') && g.s.res.wood >= JAM_UNLOCK_WOOD,
    intro: '柴房堆满了木头。收拾爷爷的老屋时，翻出奶奶留下的果酱方子，要用柴火慢慢熬。',
    line: '照着奶奶的方子试了几回，火候掌握住了。' },
  { id: 'catalog', name: '藏书', desc: '农技上限 +50%', cost: { science: 10000 }, deps: ['station'],
    line: '书屋里的书分门别类排好了，找资料快多了。', effects: { capMult: { science: 0.5 } } },
  { id: 'coldChain', name: '冷链', desc: '可以建冷库，多放果酱', cost: { science: 15000, money: 3000000 }, deps: ['jam'],
    line: '学会了冷库的门道，果酱能放得更久。' },
  // ---- 年代二：加工 ----
  { id: 'drying', name: '晾晒', desc: '果子切片晒成果干，不用柴火', cost: { science: 5000 }, deps: ['jam'],
    line: '跟村里的老人学会了晒果干，挑晴天、勤翻面。' },
  { id: 'labField', name: '实验田', desc: '可以开实验田，加农技上限', cost: { science: 6000 }, deps: ['station'],
    line: '农技站的专家说，要搞研究就得有自己的试验地。' },
  { id: 'plantation', name: '速生林', desc: '木头产量翻倍，可以建林场', cost: { science: 10000 }, deps: ['forestry', 'sawmill'],
    line: '引进了速生杨，五六年就能成材。', effects: { mult: { forest: 1 } } },
  { id: 'nutrition', name: '营养搭配', desc: '每种加工品给帮工的心情翻倍', cost: { science: 8000 }, deps: ['drying'],
    line: '食堂的饭菜讲究起了搭配，果酱、果干轮着上。', effects: { flags: ['nutrition'] } },
  { id: 'juicing', name: '榨汁', desc: '果子榨成果汁，超市和航空公司最爱', cost: { science: 12000, money: 5000000 }, deps: ['drying'],
    line: '学会了榨汁和巴氏杀菌，果汁能放好几个月。' },
  { id: 'packaging', name: '包装设计', desc: '卖东西的价钱 +15%', cost: { science: 15000 }, deps: ['juicing'],
    line: '请美院的学生设计了包装，摆上货架一下就显眼了。', effects: { mult: { price: 0.15 } } },
  { id: 'brewing', name: '酿造', desc: '果子酿成果酒，最值钱，要有酒窖', cost: { science: 20000, money: 20000000 }, deps: ['juicing'],
    line: '请来了酿酒师傅，果酒要在酒窖里慢慢等。' },
  { id: 'fermentation', name: '发酵学', desc: '酒坊效率 +50%', cost: { science: 30000 }, deps: ['brewing'],
    line: '搞懂了酵母，酒的出品稳定多了。', effects: { mult: { winery: 0.5 } } },
  { id: 'solarDrying', name: '太阳能烘干', desc: '晒架不再看季节，一年四季都按夏天算', cost: { science: 25000 }, deps: ['drying', 'mechanization'],
    line: '晒场盖上了太阳能烘干棚，冬天也能晒。', effects: { flags: ['solarDry'] } },
  { id: 'assembly', name: '流水线', desc: '作坊、锯木坊、砖窑、榨汁坊效率 +50%', cost: { science: 40000, money: 100000000 },
    deps: ['mechanization', 'juicing'], line: '各个作坊改成了流水线。', effects: { mult: { mill: 0.5, juice: 0.5 } } },
  { id: 'branding', name: '品牌', desc: '卖东西的价钱 +20%', cost: { science: 50000, money: 200000000 }, deps: ['packaging'],
    line: '注册了自己的商标，「爷爷的果园」。', effects: { mult: { price: 0.2 } } },
  // ---- 年代三：市场 ----
  { id: 'ecommerce', name: '电商', desc: '可以开网店，多一个不看面子的销路', cost: { science: 60000, money: 100000000 },
    deps: ['branding'], show: g => g.s.f.market, line: '注册了网店，请了两个大学生来管。' },
  { id: 'marketResearch', name: '市场调研', desc: '买家收满了也只降到七折', cost: { science: 70000 }, deps: ['branding'],
    show: g => g.s.f.market, line: '跑了一圈市场，摸清了各家的进货规律，错开时间送货。', effects: { flags: ['marketResearch'] } },
  { id: 'digitalLib', name: '数字图书馆', desc: '农技上限 +50%', cost: { science: 60000 }, deps: ['ecommerce'],
    line: '农技站接上了网，全国的论文都查得到。', effects: { capMult: { science: 0.5 } } },
  { id: 'livestream', name: '直播带货', desc: '网店的收购量翻倍', cost: { science: 80000 }, deps: ['ecommerce'],
    line: '在果园里开直播，一晚上卖空了库房。', effects: { mult: { online: 1 } } },
  { id: 'logistics', name: '物流网络', desc: '所有买家的收购量 +25%', cost: { science: 90000, money: 300000000 }, deps: ['ecommerce'],
    line: '和快递公司签了协议，县里建了分拣中心。', effects: { mult: { refill: 0.25 } } },
  { id: 'compoundFert', name: '复合肥', desc: '可以建化肥厂', cost: { science: 75000 }, deps: ['compost'],
    show: g => g.s.made.includes('fertilizer'), line: '学会了配复合肥，黏土和果渣都能用上。' },
  { id: 'soilTest', name: '测土配方', desc: '施肥的加成从 30% 提到 50%', cost: { science: 100000 }, deps: ['compoundFert'],
    line: '每块地都测了土，缺什么补什么。', effects: { flags: ['soilTest'] } },
  { id: 'nursery', name: '育苗', desc: '可以建苗圃，自己育良种苗木', cost: { science: 90000 }, deps: ['grafting'],
    show: g => g.s.made.includes('seedling'), line: '跟农科院学会了组培育苗。' },
  { id: 'exportCert', name: '出口认证', desc: '卖东西的价钱 +15%', cost: { science: 120000, money: 1000000000 }, deps: ['logistics'],
    line: '拿到了出口认证，包装上印了英文。', effects: { mult: { price: 0.15 } } },
  // ---- 年代四：企业 ----
  { id: 'ruralTourism', name: '乡村旅游', desc: '可以开农家饭庄、观光小火车', cost: { science: 120000 }, deps: ['branding'],
    show: g => g.s.f.tourism, line: '县文旅局来调研，说你这儿可以搞乡村旅游示范点。' },
  { id: 'homestayMgmt', name: '民宿管理', desc: '游客多 30%，花得也多 30%', cost: { science: 140000 }, deps: ['ruralTourism'],
    line: '民宿换了床品、加了早餐，网上的评分涨到了 4.9。', effects: { mult: { tourism: 0.3 } } },
  { id: 'studyTours', name: '研学旅行', desc: '每个游客每秒带来 0.02 农技', cost: { science: 150000 }, deps: ['ruralTourism'],
    line: '学校组织学生来果园研学，农技站的专家给他们上课，顺便也收集了不少数据。', effects: { flags: ['studyTours'] } },
  { id: 'resortHotel', name: '度假酒店', desc: '可以盖度假酒店，住得下更多游客', cost: { science: 160000, money: 500000000 },
    deps: ['homestayMgmt'], line: '请了酒店管理公司来做规划。' },
  { id: 'hotSpring', name: '温泉开发', desc: '可以开温泉，冬天也有游客', cost: { science: 170000, money: 1000000000 },
    deps: ['ruralTourism'], line: '地质队在后山探到了温泉水。' },
  { id: 'festivals', name: '节庆活动', desc: '游客多 25%，花得也多 25%', cost: { science: 190000 }, deps: ['homestayMgmt'],
    line: '办了第一届采摘节，开幕那天县长来剪彩。', effects: { mult: { tourism: 0.25 } } },
  { id: 'apartment', name: '员工公寓', desc: '可以盖员工公寓，每栋住 20 人', cost: { science: 100000 }, deps: ['brickHouse'],
    show: g => g.s.workers >= 100, line: '设计院出了员工公寓的图纸。' },
  { id: 'cooperative', name: '合作社', desc: '可以租邻村的地，交租金、产果子', cost: { science: 130000, money: 500000000 },
    deps: ['exportCert'], line: '牵头成立了果业合作社，邻村的人都愿意把地租给你。' },
  { id: 'modernMgmt', name: '现代管理', desc: '所有岗位的产量 +25%', cost: { science: 180000, money: 2000000000 },
    deps: ['cooperative'], line: '请了职业经理人，排班、考核都上了系统。', effects: { mult: { labor: 0.25 } } },
  { id: 'mechanization', name: '机械化', desc: '锯木坊、砖窑、果酱作坊效率翻倍', cost: { science: 20000, money: 30000000 },
    deps: ['sawmill', 'kiln'], line: '电机代替了人力，作坊的产量翻了一番。', effects: { mult: { mill: 1 } } }
];
